together-ai:
  host: 'https://api.together.xyz'
  api-key: '********'
  timeout: 30

gemini-ai:
  host: 'https://generativelanguage.googleapis.com'
  api-key: '********'
  timeout: 30

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
    validate-on-migrate: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
